# MariaDB
spring.datasource.url=jdbc:mariadb://localhost:3310/oauth2_demo
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Hibernate - JPA
spring.jpa.hibernate.ddl-auto=update
spring.jps.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# GCP OAuth2
spring.security.oauth2.client.registration.google.client-id="changeplz"
spring.security.oauth2.client.registration.google.client-secret=changeplz
spring.security.oauth2.client.registration.google.scope=email,prifile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
# sub : ??? ???? ??? ?? ???
spring.security.oauth2.client.provider.google.user-name-attribute=sub

# JWT
# frontend??? .env?? ????? ??????(car??? ??? ??)
jwt.secret=mySecretKeyForJwtTokenGenerationMustBe256BitsLong1234567890
jwt.expiration=86400000
